POST http://localhost:8000/batch/admin/job/run
Content-Type: application/json

{
  "name":"com.xingyuan.train.batch.job.DailyTrainJob",
  "jobGroupName": "default"
}

###

POST http://localhost:8000/batch/admin/job/add
Content-Type: application/json

{
  "name": "com.xingyuan.train.batch.job.DailyTrainJob",
  "jobGroupName": "default",
  "cronExpression": "*/5 * * * * ?",
  "desc": "test job"
}

###
GET http://localhost:8000/batch/admin/job/query
Accept: application/json

###
POST http://localhost:8000/batch/admin/job/pause
Content-Type: application/json

{
  "name": "com.xingyuan.train.batch.job.DailyTrainJob",
  "jobGroupName": "default"
}

###
